import { Sidebar } from "@/components/sidebar/Sidebar";
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className={`flex h-screen overflow-hidden`}>
          {/* ===== Sidebar Start ===== */}
          <div>
            <Sidebar />
          </div>
          <div className="relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden">
            {/* ===== Main Content Start ===== */}
            <main className="relative">
              <div className="mx-auto ">{children}</div>
            </main>
            {/* ===== Main Content End ===== */}
          </div>
        </div>
      </body>
    </html>
  );
}
